// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/repohive-landing/BoldOpinionated.tsx": () => import("../components/mockups/repohive-landing/BoldOpinionated.tsx"),
  "./components/mockups/repohive-landing/HackerTerminal.tsx": () => import("../components/mockups/repohive-landing/HackerTerminal.tsx"),
  "./components/mockups/repohive-landing/RawMinimal.tsx": () => import("../components/mockups/repohive-landing/RawMinimal.tsx")
};
